In [3]:
import numpy as np
import matplotlib.pyplot as plt

from warnings import warn
from scipy.special import lambertw

In [8]:
def newton_(fn, d_fn, x, tol=1E-15, max_steps=20):
  
  converged = np.zeros_like(x, dtype='bool')
  
  for _ in range(max_steps):
    
    f_x = fn(x[~converged], ~converged)
    flipped = np.abs(f_x) < tol
    
    converged[~converged] = flipped
    
    if np.all(converged):
      return x
    
    x[~converged] -= f_x[~flipped] / d_fn(x[~converged])
    
  
  warn(f"Max steps reached w/o convergence; increase tol or max_steps")
  
  return x




def lambertw_custom_1(x, tol=1E-15):
    
    def x_exp_shifted(z, mask=slice(None)):
      return z * np.exp(z) - x[mask]
    def x_exp_der(z):
      return (z + 1) * np.exp(z)
    
    init_guess = np.ones_like(x)
    init_guess[x > np.e] = np.log(x[x>np.e])-np.log(np.log(x[x>np.e]))
    
    return newton_(x_exp_shifted, x_exp_der, init_guess, tol)

In [5]:
x = np.arange(-1/np.e+1e-8, 1, 1e-6)

In [9]:
lambertw_custom_1(x, 1E-15)

array([2.33146278e-04, 2.34144485e-03, 3.30203888e-03, ...,
       1.56714241e+00, 1.56714277e+00, 1.56714313e+00])

In [3]:
import numpy as np
import numpy.polynomial.legendre as leg

In [2]:
leg.legroots((1, 2, 3, 4))

array([-0.85099543, -0.11407192,  0.51506735])

In [9]:
a=np.zeros(40)

In [10]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [11]:
a[39]=1

In [12]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [13]:
leg.legroots(a)

array([-9.98147383e-01, -9.90251537e-01, -9.76098709e-01, -9.55775212e-01,
       -9.29409148e-01, -8.97167119e-01, -8.59252938e-01, -8.15906297e-01,
       -7.67401243e-01, -7.14044436e-01, -6.56173213e-01, -5.94153455e-01,
       -5.28377269e-01, -4.59260512e-01, -3.87240164e-01, -3.12771559e-01,
       -2.36325512e-01, -1.58385340e-01, -7.94438046e-02,  1.50274291e-16,
        7.94438046e-02,  1.58385340e-01,  2.36325512e-01,  3.12771559e-01,
        3.87240164e-01,  4.59260512e-01,  5.28377269e-01,  5.94153455e-01,
        6.56173213e-01,  7.14044436e-01,  7.67401243e-01,  8.15906297e-01,
        8.59252938e-01,  8.97167119e-01,  9.29409148e-01,  9.55775212e-01,
        9.76098709e-01,  9.90251537e-01,  9.98147383e-01])